LOAD DATA LOCAL INFILE 'items.csv' INTO TABLE Items FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'categories.csv' INTO TABLE Categories FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'itemHasCategory.csv' INTO TABLE ItemHasCategory FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'sellers.csv' INTO TABLE Sellers FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'itemHasSeller.csv' INTO TABLE ItemHasSeller FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bidders.csv' INTO TABLE Bidders FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'bids.csv' INTO TABLE Bids FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'itemHasBid.csv' INTO TABLE ItemHasBid FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'coordinates.csv' INTO TABLE Coordinates FIELDS TERMINATED BY '|*|';

LOAD DATA LOCAL INFILE 'itemHasCoordinate.csv' INTO TABLE ItemHasCoordinate FIELDS TERMINATED BY '|*|';
